const PLAN_CONFIG = {
  essential_monthly: {
    planName: "Essential",
    billingCycle: "monthly",
    amount: 5,
    currency: "USD",
    features: {
      maxSuperAdmins: 1,
      maxClients: 2,
      maxSecurityGuards: 3,
      maxPostSites: 3,
      dashboard: true,
      activity: true,
      clients: true,
      securityTeam: true,
      timeClock: true,
      reportingDays: 7,
      gpsTrackingDays: 30,
      geofenceDays: 0,
      messenger: false,
      siteTourDays: 0,
      taskDays: 0,
      checklistDays: 0,
      supportLevel: "email",
    },
  },

  advanced_monthly: {
    planName: "Advanced",
    billingCycle: "monthly",
    amount: 8,
    currency: "USD",
    features: {
      maxSuperAdmins: 2,
      maxClients: 5,
      maxSecurityGuards: 6,
      maxPostSites: 6,
      dashboard: true,
      activity: true,
      clients: true,
      securityTeam: true,
      timeClock: true,
      reportingDays: 14,
      gpsTrackingDays: 60,
      geofenceDays: 60,
      messenger: true,
      siteTourDays: 0,
      taskDays: 0,
      checklistDays: 0,
      supportLevel: "standard",
    },
  },

  professional_monthly: {
    planName: "Professional",
    billingCycle: "monthly",
    amount: 10.99,
    currency: "USD",
    features: {
      maxSuperAdmins: -1,
      maxClients: -1,
      maxSecurityGuards: -1,
      maxPostSites: -1,
      dashboard: true,
      activity: true,
      clients: true,
      securityTeam: true,
      timeClock: true,
      reportingDays: 30,
      gpsTrackingDays: 90,
      geofenceDays: 90,
      messenger: true,
      siteTourDays: 90,
      taskDays: 90,
      checklistDays: 90,
      supportLevel: "24/7",
    },
  },

  essential_yearly: {
    planName: "Essential",
    billingCycle: "yearly",
    amount: 4.5,
    currency: "USD",
    features: {
      maxSuperAdmins: 2,
      maxClients: 5,
      maxSecurityGuards: 6,
      maxPostSites: 6,
      maxSuperAdmins: 1,
      maxClients: 2,
      maxSecurityGuards: 3,
      maxPostSites: 3,
      dashboard: true,
      activity: true,
      clients: true,
      securityTeam: true,
      timeClock: true,
      reportingDays: 7,
      gpsTrackingDays: 30,
      geofenceDays: 0,
      messenger: false,
      siteTourDays: 0,
      taskDays: 0,
      checklistDays: 0,
      supportLevel: "email",
    },
  },
advanced_yearly
  : {
    planName: "Advanced",
    billingCycle: "yearly",
    amount: 6.8,
    currency: "USD",
    features: {
      maxSuperAdmins: 2,
      maxClients: 5,
      maxSecurityGuards: 6,
      maxPostSites: 6,
      dashboard: true,
      activity: true,
      clients: true,
      securityTeam: true,
      timeClock: true,
      reportingDays: 14,
      gpsTrackingDays: 60,
      geofenceDays: 60,
      messenger: true,
      siteTourDays: 0,
      taskDays: 0,
      checklistDays: 0,
      supportLevel: "standard",
    },
  },

  professional_yearly: {
    planName: "Professional",
    billingCycle: "yearly",
    amount: 8.5,
    currency: "USD",
    features: {
      maxSuperAdmins: -1,
      maxClients: -1,
      maxSecurityGuards: -1,
      maxPostSites: -1,
      dashboard: true,
      activity: true,
      clients: true,
      securityTeam: true,
      timeClock: true,
      reportingDays: 30,
      gpsTrackingDays: 90,
      geofenceDays: 90,
      messenger: true,
      siteTourDays: 90,
      taskDays: 90,
      checklistDays: 90,
      supportLevel: "24/7",
    },
  },
};

module.exports = { PLAN_CONFIG };